name: hello
on: workflow_dispatch
jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - name: DEV_JOB
        run: |
          echo "hello from dev" 
          echo "abu"
  Test:
    runs-on: ubutu-latest
    steps:
      - name: Test_job
        run: echo "hello from test"

  Production:
    runs-on: ubuntu-latest
    steps:
      - name: Production_job
        run: echo "hello from production"
    
    
        
        
  
